### ISSUE TITLE
Apply for EIN with IRS

### ISSUE THREAD

**Issue by dlindahl** [techramento/techramento.github.io#15]

**Comment by dlindahl** [comment]
Blocked until #14 is closed

**Comment by dlindahl** [comment]
See [Incorporators Statement](https://github.com/techramento/techramento.github.io/blob/ff7717a0b56b2349f9a3073329983350eec6e80c/corporate_records/incorporators_statement.md#L1) for board member info

**Comment by dlindahl** [comment]
Tabled to next meeting (in order to be tabled to the next meeting :smile:)

**Comment by roughani** [comment]
Needs to be done within 90 days of incorporating. Can be filed online here: 
https://businessfilings.sos.ca.gov/

**Comment by roughani** [comment]
Needs to be done prior to filing exemption application #22.

**Comment by efletch** [comment]
EIN acquired! Contact me if it is needed for tasks. Will share securely once we have a secure method in place.
