### ISSUE TITLE
File Statement of Information with Secretary of State

### ISSUE THREAD

**Issue by roughani** [techramento/techramento.github.io#21]
Needs to be done within 90 days of incorporating. Can be filed online here: 
https://businessfilings.sos.ca.gov/

**Comment by dlindahl** [comment]
This has been filed. Waiting on an email receipt.

**Comment by roughani** [comment]
w00t!

**Comment by dlindahl** [comment]
Here is the Statement of Information receipt: [FC47694.pdf](https://github.com/techramento/techramento.github.io/files/211872/FC47694.pdf)
