### ISSUE TITLE
File Federal Exemption Application with Internal Revenue Service

### ISSUE THREAD

**Issue by roughani** [techramento/techramento.github.io#22]
We're eligible to file Form 1023-EZ if we project that annual gross receipts will not exceed $50k in the next three years. If we receive federal exemption, that will automatically qualify us for state exemption saving us from needing to file an additional (more complex) application.
- [About Form 1023-EZ](https://www.irs.gov/uac/About-Form-1023EZ)
- Instructions ([PDF](https://www.irs.gov/pub/irs-pdf/i1023ez.pdf)) ([HTML](https://www.irs.gov/instructions/i1023ez/index.html))
- Eligibility Worksheet (must be completed and retained as corporate record prior to completing online appication) ([PDF](https://www.irs.gov/pub/irs-pdf/i1023ez.pdf#page=11)) ([HTML](https://www.irs.gov/instructions/i1023ez/ar02.html))
- [Pay.gov Online Form 1023-EZ](https://pay.gov/public/form/start/62759871)

**COST**: $400

**Comment by dlindahl** [comment]
I authorize @rjulian to sign the 1023EZ document on behalf of the organization.

**Comment by dlindahl** [comment]
This was completed by @roughani at the April 10th meeting:

Receipt:

```
  Application Name: Form 1023-EZ
  Pay.gov Tracking ID: 25QVKI76
  Agency Tracking ID: 74993931964

  Account Holder Name: Techramento
  Transaction Type: ACH Debit
  Transaction Amount: $400.00
  Payment Date: 04/12/2016
  Account Type: Business Checking
  Routing Number: 121122676
  Account Number: ************8326

  Transaction Date: 04/10/2016 04:12:41 PM EDT
  Total Payments Scheduled: 1
  Frequency: OneTime
```
