### ISSUE TITLE
Understand and comply with the Attorney General California Nonprofit Integrity Act of 2004

### ISSUE THREAD

**Issue by roughani** [techramento/techramento.github.io#25]
@techramento/owners Please read and comment that you acknowledge Techramento's need to comply with the California Nonprofit Integrity Act of 2004:
http://ag.ca.gov/charities/publications/nonprofit_integrity_act_nov04.pdf
- [x] @dlindahl
- [x] @rjulian 
- [x] @efletch 
- [x] @roughani

**Comment by dlindahl** [comment]
Added checkboxes for each board member

**Comment by dlindahl** [comment]
I have read, understand, and will comply with California's Nonprofit Integrity Act of 2004.

**Comment by rjulian** [comment]
I have read, understand, and will comply with California's Nonprofit Integrity Act of 2004.

**Comment by efletch** [comment]
I have read, understand, and will comply with California's Nonprofit Integrity Act of 2004.

**Comment by roughani** [comment]
I have read, understand, and will comply with California's Nonprofit Integrity Act of 2004.
