### ISSUE TITLE
City of Sacramento Innovation and Growth Fund

### ISSUE THREAD

**Issue by roughani** [techramento/techramento.github.io#26]
Mayor Kevin Johnson announced in his State of the City address that the City of Sacramento would be using its Innovation and Growth Fund to support the local tech community.

Motion: Should we reach out to the city to ask what information they need from us to qualify for financial support?
- [x] @dlindahl 
- [x] @efletch 
- [ ] @rjulian

**Comment by dlindahl** [comment]
@roughani will come up with a dollar amount and a (more or less) itemized account of what that money would go towards which will go in our application for this Fund.

Things to include will be video recording equipment and general funds to distribute to member organizations. If we source video equipment elsewhere, we will strike that from the ask.

**Comment by dlindahl** [comment]
We need to come up with a budget to describe what the funding would go towards (video rental equipment, conference expenses, etc.)

I will come up with a rough budget to kick off the discussion.

**Comment by dlindahl** [comment]
Budget considerations are captured in #31

**Comment by dlindahl** [comment]
Due to the Conflict of Interest policy for the RAILS grants, Techramento cannot apply for money directly. However, we can streamline the process so that member organizations can apply on their own without too much extra leg work.

@dlindahl will work with @roughani on a SacJS proposal so that we can nail down the particular of that process.

**Comment by roughani** [comment]
City Attorney says Techramento cannot be a fiscal sponsor for any orgs awarded a RAILS grant. The issue is that any contract between the City and Techramento constitutes a financial interest on my behalf, regardless of whether the purpose is to fund Techramento itself or an organization it's sponsoring. 

I'm going to close this issue given that Techramento should not have any relationship with the City's Innovation & Growth Fund, as long as I'm both a member of the board of directors of Techramento and an employee of the City implementing the RAILS grant program.
