### ISSUE TITLE
File State Exemption Application with Franchise Tax Board

### ISSUE THREAD

**Issue by roughani** [techramento/techramento.github.io#27]
FTB 3500A, Submission of Exemption Request

> This form can only be used by organizations that have a federal determination letter under Internal Revenue Code (IRC) Section 501(c)(3), (c)(4), (c)(5), (c)(6), or (c)(7). No other IRC sections under 501(a) can be used with the FTB 3500A. There is no filing fee for this form.
> 
> With the submission of FTB 3500A and a copy of the federal determination letter, we will send an acknowledgement letter that states the entity is recognized as having California tax-exempt status.

via https://www.ftb.ca.gov/businesses/Exempt_organizations/Applying_for_tax-exemption.shtml#Submission_Exempt_Request

**[FTB Form 3500A](https://www.ftb.ca.gov/forms/misc/3500a.pdf)**

**Comment by dlindahl** [comment]
@roughani I made a quick pass over the 3500A and put in on the Google Drive if you want to double check it

**Comment by roughani** [comment]
Cool. I'm adding our corporation number and clarifying that we're not
applying for group exemption (Part II, Question 6), as that's for exempting
multiple organizations.

Only question is re: Part III, Question 1. In our 1023-EZ application, we
requested exemption for educational AND charitable purposes. Does the IRS
exemption letter state that we qualified under both purposes? If so, we
need to also check the charitable box for Part III, Question 1. Let me know
and I'll upload the updated 3500A.

**Comment by dlindahl** [comment]
Relevant bits extracted from letter:

```
Public Charity Status:
  170(b)(1)(A)(vi)
Form 990/990-EZ/990-N Required:
  Yes
```

> You're also qualified to receive tax deductible bequests, devises, transfers or gifts under Section 2055, 2106, 2522.
> 
> For more information about your responsibilities as a tax-exempt organization, go to ww.irs.gov/charities. Enter "4221-PC" in the search bar to view Publication 4221-PC, Compliance Guide for 501(c)(3) Public Charities, which describes your recordkeeping, reporting, and disclosure requirements.

That line sounded like a "pick one" to me (since it said "Primary") so I picked "Educational". If we applied for both, maybe we should check both? I'm not sure...

**Comment by roughani** [comment]
We applied for both on 1023-EZ and the form says **check all that apply**:

<img width="742" alt="screen shot 2016-04-22 at 11 25 21 am" src="https://cloud.githubusercontent.com/assets/4371233/14751076/0d1b6f32-087d-11e6-8b2a-b822f861782f.png">

**Comment by dlindahl** [comment]
@roughani I meant on the 3500A:

![screen shot 2016-04-22 at 11 27 28 am](https://cloud.githubusercontent.com/assets/55945/14751133/436c48d6-087d-11e6-9a96-fab4301feacf.png)

"primary"

Can you have two "primary" purposes? ¯_(ツ)_/¯

**Comment by roughani** [comment]
Yeah, it's confusing, but everything I've read suggests you can have multiple primary purposes. And since federal law is the overriding concern, I think it's just a matter of aligning our state exemption with our federal exemption. So I uploaded the new version to Google Drive with both boxes checked.

**Comment by dlindahl** [comment]
I concur 🍻 

Thoughts on the $50k estimated gross for the year? Too high? Too low? On target?

**Comment by roughani** [comment]
It's a nice goal, but now that I think about it... most organizations expect their revenues to go up every year and since $50k is our cap for the first three years maybe $30k for yr. 1, $40k for yr. 2, and $50k for yr. 3 would also work. They're just estimates, though, so we don't need to put too much thought into it. I think they just want to ball park because all of that language about audits and using professional fundraisers mentioned in the Nonprofit Integrity Act once you get into the millions.

**Comment by dlindahl** [comment]
So leave it as $50k or reduce it to $30k? I assumed this form is a one-time filing but maybe thats not accurate?

**Comment by roughani** [comment]
$50k is good since we don't plan to exceed that amount. This is a one-time
form; once we're granted exemption, we stay exempt unless we break the
rules. Besides state and federal tax returns, the only other form we'll
need to file annually is our Statement of Information with the Secretary of
State, which lets them know if we've changed officers or our addresses.

**Comment by dlindahl** [comment]
Paperwork filled out and in an envelope. I only need to drop it in a mailbox!

**Comment by dlindahl** [comment]
Mailed!
