### ISSUE TITLE
Logo Questionnaire Answers

### ISSUE THREAD

**Issue by dlindahl** [techramento/techramento.github.io#34]
Here are the merged answers to Meritt's branding questionnaire. Comment if you have any changes or issues. Once you are :100: on sending this on to Meritt, check-off your name:
- [x] @dlindahl
- [x] @rjulian 
- [x] @efletch 
- [X] @roughani 

---
## What are your business objectives?

We're a meta organization that hopes to bring unity to the currently siloed community builders in the Sacramento tech community and provide a voice to its members. This will increase the visibility and cohesiveness of the community and encourage investment, both inside and outside of our region, and growth through our grassroots efforts of providing marketing, advice, and resources.
## What is the company mission and vision

We want to have not just "a" community, but a community that is a good example of what others are capable of. By empowering individuals to put on the best events they can, we can build a strong and sustainable tech community that encourages personal growth, shared innovation, and opportunity.
## How would you like to be perceived by others

Co-creating the future of Sacramento, being organized, building a community, increasing skills, and being an open, welcoming, inviting, forward-thinking platform to not just different skill levels or technologies, but of backgrounds as well.

We want to help people as good stewards of the local tech community and be a value add to the community, not an impediment or bureaucratic gateway.
## Who is your primary target market

Inclusive to all technologists of any skill level and interest to include current leaders as well as those in the general public with no previous exposure to our community and everyone in-between.
## What do you offer your target market that others do not

A high standard of quality. You know a Techramento affiliated event will have a high bar of quality. We can leverage our connections to businesses and leaders both inside and outside of Sacramento to help bring in the resources our members need that they might otherwise be incapable of receiving.
## What do you want your logo to say about your business

We're a local, grassroots organization that is open and welcoming technologists in Sacramento.
## What keywords best describe your business
- coalition
- community
- empowering
- exposure
- general public
- growth
- leadership
- learning
- mentoring
- progress
- quality
- supportive
- sacramento
- sharing
- unity
- welcoming

**Comment by roughani** [comment]
+1

**Comment by efletch** [comment]
A+

**Comment by dlindahl** [comment]
Sent to Meritt.
