### ISSUE TITLE
Should Techramento join tech company recruitment partnership?

### ISSUE THREAD

**Issue by roughani** [techramento/techramento.github.io#38]
The City of Sacramento is considering a partnership with the [Greater Sacramento Economic Council](https://www.selectsacramento.com/) to use a collaborative CRM solution (Salesforce) to manage tech company recruitment efforts. Techramento may be able to join this partnership and provide the Salesforce instance for this effort through the free licenses offered under their [Power of Us](http://www.salesforce.org/nonprofit/power-of-us/) program. Approval to participate would not authorize the use of any Techramento funds in this collaboration.

@techramento/board needs approve by the usual checkbox format and by commenting their official approval
- [ ] @dlindahl
- [x] @rjulian 
- [x] @efletch 
- [x] @roughani

**Comment by roughani** [comment]
I approve.

**Comment by dlindahl** [comment]
Is this a vote to formally join in partnership, or is this a vote to start a discussion w/ the Council about what a partnership would entail?

**Comment by roughani** [comment]
No longer an active opportunity.
