### ISSUE TITLE
Verify costs of creating legal entity and minimum franchise tax

### ISSUE THREAD

**Issue by dlindahl** [techramento/techramento.github.io#4]

**Comment by dlindahl** [comment]
This has been researched but needs to be codified.

**Comment by roughani** [comment]
Filing fees are as follows:

| Step | Agency | Fee |
| --- | --- | --- |
| Reserve corporate name | Secretary of State | $20 |
| File Articles of Incorporation | Secretary of State | $30 + $15 fee in person |
| File Statement of Information | Secretary of State | $20 |
| State Exemption Application | Franchise Tax Board Form | $25 (free if IRS grants exemption |
| IRS Exemption Application (Form 2023 EZ) | Internal Revenue Service | $400 |
| Register with Registry of Charitable Trusts | Attorney General | $25 |
| &nbsp; | **TOTAL** | **$495** to **$535** |

For a description of all required steps, check out the [Wiki: Basic Steps for Starting a California Nonprofit](https://github.com/techramento/techramento.github.io/wiki/Basic-Steps-for-Starting-a-California-Nonprofit).

I've confirmed that exempt organizations are not subject to the [minimum franchise tax](https://www.ftb.ca.gov/businesses/faq/712.shtml) (hence, why they're "tax exempt"!). Confusion arose from the scenario in which the organization incorporates, but does not receive its exempt status until the following tax year. While we would be required to pay the $800 minimum franchise tax, it would be [refunded retroactively](https://www.ftb.ca.gov/businesses/Exempt_organizations/The_Process.shtml#Retroactive_tax_exempt_status) if we eventually received the exemption. However, we should be able to avoid all of this by starting the process in January.

**Comment by dlindahl** [comment]
Discussed at our meeting on 2015-12-30
