### ISSUE TITLE
Verify requirements for opening a bank account for a non-profit

### ISSUE THREAD

**Issue by dlindahl** [techramento/techramento.github.io#6]

**Comment by dlindahl** [comment]
@roughani says that we need to incorporate first

**Comment by roughani** [comment]
We'll also need an [Employer Identification Number](https://www.irs.gov/Businesses/Small-Businesses-&-Self-Employed/Employer-ID-Numbers-EINs), but we can get that immediately online after the Secretary of State confirms our Articles of Incorporation are legit.

**Comment by efletch** [comment]
US Bank Checking Account for Nonprofits: https://www.usbank.com/small-business/checking/nonprofits.html

Requirements
- Employer Identification Number
-  A charter, articles of organization, or similar legal document that shows when your organization was formed
- A charter or other official document that lists the officers of your organization
- A government-issued photo ID and Social Security numbers for you and anyone else authorized to sign checks or make transactions on behalf of your organization

**Comment by dlindahl** [comment]
As discussed with @efletch, we need to determine if photocopies of photo IDs is OK or if we all need to be there in person.
